/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Admin
 */
public class Jugador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Jugador
     */
    public Jugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelSobreFondo = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelSeleccionarPerfil = new javax.swing.JLabel();
        jButtonCrearPerfil = new javax.swing.JButton();
        jLabelNickname = new javax.swing.JLabel();
        jLabelPartidasJugadas = new javax.swing.JLabel();
        jLabelDineroObtenido = new javax.swing.JLabel();
        jLabelUserNickname = new javax.swing.JLabel();
        jLabelUserPartidasJugadas = new javax.swing.JLabel();
        jLabelUserDineroObtenido = new javax.swing.JLabel();
        jLabelDineroObtenido1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 153));
        setMaximumSize(new java.awt.Dimension(1024, 740));
        setMinimumSize(new java.awt.Dimension(1024, 740));
        setPreferredSize(new java.awt.Dimension(1024, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setBackground(new java.awt.Color(0, 64, 96));
        jPanelFondo.setMaximumSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setMinimumSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSobreFondo.setBackground(new java.awt.Color(0, 73, 110));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelSeleccionarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSeleccionarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccionarPerfil.setText("Seleccionar Perfil");

        jButtonCrearPerfil.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonCrearPerfil.setText("Crear Perfil");
        jButtonCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPerfilActionPerformed(evt);
            }
        });

        jLabelNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNickname.setText("Nickname: ");

        jLabelPartidasJugadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPartidasJugadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPartidasJugadas.setText("Partidas Jugadas: ");

        jLabelDineroObtenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDineroObtenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDineroObtenido.setText("Dinero Obtenido:");

        jLabelUserNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserNickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserNickname.setText("Invitado");

        jLabelUserPartidasJugadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserPartidasJugadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserPartidasJugadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserPartidasJugadas.setText("0");

        jLabelUserDineroObtenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserDineroObtenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserDineroObtenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserDineroObtenido.setText("0");

        jLabelDineroObtenido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDineroObtenido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDineroObtenido1.setText("HISTORIAL DE PARTIDAS:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Partida", "Rondas Ganadas", "Dinero Obtenido"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelSobreFondoLayout = new javax.swing.GroupLayout(jPanelSobreFondo);
        jPanelSobreFondo.setLayout(jPanelSobreFondoLayout);
        jPanelSobreFondoLayout.setHorizontalGroup(
            jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNickname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserNickname)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                        .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDineroObtenido1)
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelDineroObtenido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserDineroObtenido))
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelPartidasJugadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserPartidasJugadas)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSobreFondoLayout.createSequentialGroup()
                        .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelSeleccionarPerfil)
                                .addGap(45, 45, 45)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                                .addComponent(jButtonCrearPerfil)))
                        .addGap(81, 81, 81))))
        );
        jPanelSobreFondoLayout.setVerticalGroup(
            jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeleccionarPerfil)
                    .addComponent(jButtonCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickname)
                    .addComponent(jLabelUserNickname))
                .addGap(18, 18, 18)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartidasJugadas)
                    .addComponent(jLabelUserPartidasJugadas))
                .addGap(18, 18, 18)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDineroObtenido)
                    .addComponent(jLabelUserDineroObtenido))
                .addGap(18, 18, 18)
                .addComponent(jLabelDineroObtenido1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelSobreFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 900, 610));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearPerfil;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelDineroObtenido;
    private javax.swing.JLabel jLabelDineroObtenido1;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelPartidasJugadas;
    private javax.swing.JLabel jLabelSeleccionarPerfil;
    private javax.swing.JLabel jLabelUserDineroObtenido;
    private javax.swing.JLabel jLabelUserNickname;
    private javax.swing.JLabel jLabelUserPartidasJugadas;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelSobreFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
