/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Fabrica;
import Logica.Interfaz.IControladorJugador;
import Logica.Interfaz.IControladorPartida;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Jugador extends javax.swing.JInternalFrame {

    private IControladorJugador ICJUG;
    private IControladorPartida ICPAR;
    private List<Logica.Clases.Jugador> jugadores;
    private List<Logica.Clases.Partida> partidas;

    public Jugador() {
        initComponents();
        this.ICJUG = Fabrica.getInstance().getIControladorJugador();
        this.ICPAR = Fabrica.getInstance().getIControladorPartida();
        this.jugadores = this.ICJUG.obtenerJugadores();
        rellenarComboBoxNicknameJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameCrearJugador = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelCrearJugadorNombre = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jPanelFondo = new javax.swing.JPanel();
        jPanelSobreFondo = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelSeleccionarPerfil = new javax.swing.JLabel();
        jButtonCrearPerfil = new javax.swing.JButton();
        jLabelNickname = new javax.swing.JLabel();
        jLabelPartidasGanadas = new javax.swing.JLabel();
        jLabelDineroObtenido = new javax.swing.JLabel();
        jLabelUserNickname = new javax.swing.JLabel();
        jLabelUserPartidasGanadas = new javax.swing.JLabel();
        jLabelUserDineroObtenido = new javax.swing.JLabel();
        jLabelDineroObtenido1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelPartidasJugadas = new javax.swing.JLabel();
        jLabelUserPartidasJugadas = new javax.swing.JLabel();
        jLabelAcertadas = new javax.swing.JLabel();
        jLabelUserAcertadas = new javax.swing.JLabel();

        jFrameCrearJugador.setTitle("Añadir Jugador");
        jFrameCrearJugador.setMaximumSize(new java.awt.Dimension(400, 150));
        jFrameCrearJugador.setMinimumSize(new java.awt.Dimension(400, 150));
        jFrameCrearJugador.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 150));

        jLabelCrearJugadorNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCrearJugadorNombre.setText("Nickname");

        jButtonCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCrear)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCrearJugadorNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCrearJugadorNombre)
                    .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameCrearJugadorLayout = new javax.swing.GroupLayout(jFrameCrearJugador.getContentPane());
        jFrameCrearJugador.getContentPane().setLayout(jFrameCrearJugadorLayout);
        jFrameCrearJugadorLayout.setHorizontalGroup(
            jFrameCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrameCrearJugadorLayout.setVerticalGroup(
            jFrameCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(0, 102, 153));
        setMaximumSize(new java.awt.Dimension(1024, 740));
        setMinimumSize(new java.awt.Dimension(1024, 740));
        setPreferredSize(new java.awt.Dimension(1024, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setBackground(new java.awt.Color(0, 64, 96));
        jPanelFondo.setMaximumSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setMinimumSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(1024, 740));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSobreFondo.setBackground(new java.awt.Color(0, 73, 110));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelSeleccionarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSeleccionarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccionarPerfil.setText("Seleccionar Perfil");

        jButtonCrearPerfil.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonCrearPerfil.setText("Crear Perfil");
        jButtonCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPerfilActionPerformed(evt);
            }
        });

        jLabelNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNickname.setText("Nickname: ");

        jLabelPartidasGanadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPartidasGanadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPartidasGanadas.setText("Partidas Ganadas: ");

        jLabelDineroObtenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDineroObtenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDineroObtenido.setText("Dinero Obtenido:");

        jLabelUserNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserNickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserNickname.setText("Invitado");

        jLabelUserPartidasGanadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserPartidasGanadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserPartidasGanadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserPartidasGanadas.setText("0");

        jLabelUserDineroObtenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserDineroObtenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserDineroObtenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserDineroObtenido.setText("0");

        jLabelDineroObtenido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDineroObtenido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDineroObtenido1.setText("HISTORIAL DE PARTIDAS:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Partida", "Rondas Ganadas", "Dinero Obtenido"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        jLabelPartidasJugadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPartidasJugadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPartidasJugadas.setText("Partidas Jugadas");

        jLabelUserPartidasJugadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserPartidasJugadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserPartidasJugadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserPartidasJugadas.setText("0");

        jLabelAcertadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAcertadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAcertadas.setText("Respuestas Acertadas");

        jLabelUserAcertadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserAcertadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserAcertadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserAcertadas.setText("0");

        javax.swing.GroupLayout jPanelSobreFondoLayout = new javax.swing.GroupLayout(jPanelSobreFondo);
        jPanelSobreFondo.setLayout(jPanelSobreFondoLayout);
        jPanelSobreFondoLayout.setHorizontalGroup(
            jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSobreFondoLayout.createSequentialGroup()
                        .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelSeleccionarPerfil)
                                .addGap(45, 45, 45)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                                .addComponent(jButtonCrearPerfil)))
                        .addGap(81, 81, 81))
                    .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                        .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelDineroObtenido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserDineroObtenido))
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelNickname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserNickname))
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelPartidasJugadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserPartidasJugadas))
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelAcertadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserAcertadas))
                            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                                .addComponent(jLabelPartidasGanadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUserPartidasGanadas))
                            .addComponent(jLabelDineroObtenido1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelSobreFondoLayout.setVerticalGroup(
            jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreFondoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeleccionarPerfil)
                    .addComponent(jButtonCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickname)
                    .addComponent(jLabelUserNickname))
                .addGap(7, 7, 7)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartidasJugadas)
                    .addComponent(jLabelUserPartidasJugadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartidasGanadas)
                    .addComponent(jLabelUserPartidasGanadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAcertadas)
                    .addComponent(jLabelUserAcertadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSobreFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDineroObtenido)
                    .addComponent(jLabelUserDineroObtenido))
                .addGap(29, 29, 29)
                .addComponent(jLabelDineroObtenido1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelSobreFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 900, 610));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPerfilActionPerformed
        Dimension desktopSize = Main.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jFrameCrearJugador.getSize();
        jFrameCrearJugador.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        jFrameCrearJugador.setVisible(true);
        jFrameCrearJugador.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonCrearPerfilActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        if (this.ICJUG.ingresarJugador(this.jTextFieldNickname.getText())) {
            JOptionPane.showMessageDialog(this, "Jugador agregado con éxito.");
            jFrameCrearJugador.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Es posible que el nickname ingresado ya exista.");
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        this.jLabelUserNickname.setText(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getNickname());
        this.jLabelUserDineroObtenido.setText(Integer.toString(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getDineroObtenido()));
        this.jLabelUserPartidasGanadas.setText(Integer.toString(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getPartidasGanadas()));
        this.jLabelUserAcertadas.setText(Integer.toString(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getRespuestasAcertadas()));
        this.jLabelUserPartidasJugadas.setText(Integer.toString(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getPartidasJugadas()));
        rellenarTableHistorialPartidas((DefaultTableModel) this.jTable1.getModel());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public void rellenarComboBoxNicknameJugadores() {
        for (int i = 0; i < this.jugadores.size(); i++) {
            this.jComboBox1.addItem(this.jugadores.get(i).getNickname());
        }
    }

    public void rellenarTableHistorialPartidas(DefaultTableModel tablaModelo) {
        this.partidas = this.ICPAR.obtenerPartidasDeJugador(this.jugadores.get(this.jComboBox1.getSelectedIndex()).getNickname());
        tablaModelo.setRowCount(0);
        for (int i = this.partidas.size()-1; i >= 0; i--) {
            String datos[] = {Integer.toString(i + 1), Integer.toString(this.partidas.get(i).getRondasGanadas()), Integer.toString(this.partidas.get(i).getDineroGanado())};
            tablaModelo.addRow(datos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrearPerfil;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrameCrearJugador;
    private javax.swing.JLabel jLabelAcertadas;
    private javax.swing.JLabel jLabelCrearJugadorNombre;
    private javax.swing.JLabel jLabelDineroObtenido;
    private javax.swing.JLabel jLabelDineroObtenido1;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelPartidasGanadas;
    private javax.swing.JLabel jLabelPartidasJugadas;
    private javax.swing.JLabel jLabelSeleccionarPerfil;
    private javax.swing.JLabel jLabelUserAcertadas;
    private javax.swing.JLabel jLabelUserDineroObtenido;
    private javax.swing.JLabel jLabelUserNickname;
    private javax.swing.JLabel jLabelUserPartidasGanadas;
    private javax.swing.JLabel jLabelUserPartidasJugadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelSobreFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNickname;
    // End of variables declaration//GEN-END:variables
}
