/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Clases.Categoria;
import Logica.Clases.Pregunta;
import Logica.Fabrica;
import Logica.Interfaz.IControladorCategoria;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class Partida extends javax.swing.JInternalFrame {

    private IControladorCategoria ICCAT;

    public Partida() {
        initComponents();
        this.ICCAT = Fabrica.getInstance().getIControladorCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelPreguntaCategoria = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jPanelOpcionesPreguntas = new javax.swing.JPanel();
        jPanelOpcion1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelOpcion2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelOpcion3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelOpcion4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonResponder = new javax.swing.JButton();
        jButtonRetirarse = new javax.swing.JButton();
        jPanelRondas = new javax.swing.JPanel();
        jLabelRondaTitulo = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jPanelPremios = new javax.swing.JPanel();
        jLabelPremioAcumuladoTitulo = new javax.swing.JLabel();
        jLabelPremioAcumuladoNum = new javax.swing.JLabel();
        jLabelPremioActualTitulo = new javax.swing.JLabel();
        jLabelPremioActualNum = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));
        setMaximumSize(new java.awt.Dimension(1024, 740));
        setMinimumSize(new java.awt.Dimension(1024, 740));
        setPreferredSize(new java.awt.Dimension(1024, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setBackground(new java.awt.Color(0, 64, 96));

        jPanelPreguntaCategoria.setBackground(new java.awt.Color(0, 64, 96));

        jLabelPregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPregunta.setText("PREGUNTA: ¿Puede que esa una pregunta de prueba? ");

        jLabelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCategoria.setText("CATEGORÍA: Prueba");

        javax.swing.GroupLayout jPanelPreguntaCategoriaLayout = new javax.swing.GroupLayout(jPanelPreguntaCategoria);
        jPanelPreguntaCategoria.setLayout(jPanelPreguntaCategoriaLayout);
        jPanelPreguntaCategoriaLayout.setHorizontalGroup(
            jPanelPreguntaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPreguntaCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPreguntaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPregunta)
                    .addComponent(jLabelCategoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPreguntaCategoriaLayout.setVerticalGroup(
            jPanelPreguntaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPreguntaCategoriaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabelPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCategoria)
                .addGap(12, 12, 12))
        );

        jPanelOpcionesPreguntas.setBackground(new java.awt.Color(0, 73, 110));
        jPanelOpcionesPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpcion1.setMaximumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion1.setMinimumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion1.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Esta es la primera opcion de una respuesta de prueba");

        javax.swing.GroupLayout jPanelOpcion1Layout = new javax.swing.GroupLayout(jPanelOpcion1);
        jPanelOpcion1.setLayout(jPanelOpcion1Layout);
        jPanelOpcion1Layout.setHorizontalGroup(
            jPanelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanelOpcion1Layout.setVerticalGroup(
            jPanelOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcion1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jPanelOpcionesPreguntas.add(jPanelOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 750, -1));

        jPanelOpcion2.setMaximumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion2.setMinimumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion2.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Esta es la segunda opcion de una respuesta de prueba");

        javax.swing.GroupLayout jPanelOpcion2Layout = new javax.swing.GroupLayout(jPanelOpcion2);
        jPanelOpcion2.setLayout(jPanelOpcion2Layout);
        jPanelOpcion2Layout.setHorizontalGroup(
            jPanelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanelOpcion2Layout.setVerticalGroup(
            jPanelOpcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcion2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );

        jPanelOpcionesPreguntas.add(jPanelOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 118, 750, -1));

        jPanelOpcion3.setMaximumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion3.setMinimumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion3.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Esta es la tercera opcion de una respuesta de prueba");

        javax.swing.GroupLayout jPanelOpcion3Layout = new javax.swing.GroupLayout(jPanelOpcion3);
        jPanelOpcion3.setLayout(jPanelOpcion3Layout);
        jPanelOpcion3Layout.setHorizontalGroup(
            jPanelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcion3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanelOpcion3Layout.setVerticalGroup(
            jPanelOpcion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcion3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(26, 26, 26))
        );

        jPanelOpcionesPreguntas.add(jPanelOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 206, 750, -1));

        jPanelOpcion4.setMaximumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion4.setMinimumSize(new java.awt.Dimension(815, 70));
        jPanelOpcion4.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Esta es la ultima opcion de una respuesta de prueba");

        javax.swing.GroupLayout jPanelOpcion4Layout = new javax.swing.GroupLayout(jPanelOpcion4);
        jPanelOpcion4.setLayout(jPanelOpcion4Layout);
        jPanelOpcion4Layout.setHorizontalGroup(
            jPanelOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcion4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        jPanelOpcion4Layout.setVerticalGroup(
            jPanelOpcion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcion4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26))
        );

        jPanelOpcionesPreguntas.add(jPanelOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 294, 750, -1));

        jButtonResponder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonResponder.setText("RESPONDER SELECCIONADA");

        jButtonRetirarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRetirarse.setText("RETIRARSE");
        jButtonRetirarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarseActionPerformed(evt);
            }
        });

        jPanelRondas.setBackground(new java.awt.Color(0, 64, 96));

        jLabelRondaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelRondaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRondaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRondaTitulo.setText("RONDA: ");

        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNumero.setText("1");

        javax.swing.GroupLayout jPanelRondasLayout = new javax.swing.GroupLayout(jPanelRondas);
        jPanelRondas.setLayout(jPanelRondasLayout);
        jPanelRondasLayout.setHorizontalGroup(
            jPanelRondasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRondasLayout.createSequentialGroup()
                .addComponent(jLabelRondaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumero)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelRondasLayout.setVerticalGroup(
            jPanelRondasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRondasLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanelRondasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRondaTitulo)
                    .addComponent(jLabelNumero))
                .addGap(16, 16, 16))
        );

        jPanelPremios.setBackground(new java.awt.Color(0, 64, 96));

        jLabelPremioAcumuladoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPremioAcumuladoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPremioAcumuladoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPremioAcumuladoTitulo.setText("Premio acumulado: ");

        jLabelPremioAcumuladoNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPremioAcumuladoNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPremioAcumuladoNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPremioAcumuladoNum.setText("0");

        jLabelPremioActualTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPremioActualTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPremioActualTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPremioActualTitulo.setText("Premio actual: ");

        jLabelPremioActualNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPremioActualNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPremioActualNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPremioActualNum.setText("0");

        javax.swing.GroupLayout jPanelPremiosLayout = new javax.swing.GroupLayout(jPanelPremios);
        jPanelPremios.setLayout(jPanelPremiosLayout);
        jPanelPremiosLayout.setHorizontalGroup(
            jPanelPremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiosLayout.createSequentialGroup()
                .addGroup(jPanelPremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPremiosLayout.createSequentialGroup()
                        .addComponent(jLabelPremioActualTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPremioActualNum))
                    .addGroup(jPanelPremiosLayout.createSequentialGroup()
                        .addComponent(jLabelPremioAcumuladoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPremioAcumuladoNum)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPremiosLayout.setVerticalGroup(
            jPanelPremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiosLayout.createSequentialGroup()
                .addGroup(jPanelPremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPremioAcumuladoTitulo)
                    .addComponent(jLabelPremioAcumuladoNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPremioActualTitulo)
                    .addComponent(jLabelPremioActualNum))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jPanelPreguntaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(337, Short.MAX_VALUE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRetirarse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResponder, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelPremios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelOpcionesPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanelPreguntaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                        .addComponent(jPanelRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelPremios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRetirarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelOpcionesPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetirarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarseActionPerformed

    }//GEN-LAST:event_jButtonRetirarseActionPerformed

    public void mostrarPreguntas() {
        List<Categoria> test = this.ICCAT.crearCategoriasConPreguntas();
        for (int i = 0; i < test.size(); i++) {
            System.out.println("COMPLEJIDAD:" + test.get(i).getNivelDeComplejidad());
            System.out.println("CATEGORÍA:" + test.get(i).getNombre());
            List<Pregunta> test2 = new ArrayList<>();
            test2 = test.get(i).getPreguntas();
            for (int j = 0; j < test2.size(); j++) {
                System.out.println(test2.get(j).getPregunta());
                System.out.println(test2.get(j).getRespuestaCorrecta());
                List<String> test3incorrectas = new ArrayList<>();
                test3incorrectas = test2.get(j).getRespuestasIncorrectas();
                for (int h = 0; h < test3incorrectas.size(); h++) {
                    System.out.println(test3incorrectas.get(h));
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResponder;
    private javax.swing.JButton jButtonRetirarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPremioActualNum;
    private javax.swing.JLabel jLabelPremioActualTitulo;
    private javax.swing.JLabel jLabelPremioAcumuladoNum;
    private javax.swing.JLabel jLabelPremioAcumuladoTitulo;
    private javax.swing.JLabel jLabelRondaNumero1;
    private javax.swing.JLabel jLabelRondaTitulo;
    private javax.swing.JLabel jLabelRondaTitulo1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelOpcion1;
    private javax.swing.JPanel jPanelOpcion2;
    private javax.swing.JPanel jPanelOpcion3;
    private javax.swing.JPanel jPanelOpcion4;
    private javax.swing.JPanel jPanelOpcionesPreguntas;
    private javax.swing.JPanel jPanelPreguntaCategoria;
    private javax.swing.JPanel jPanelPremios;
    private javax.swing.JPanel jPanelRondas;
    private javax.swing.JPanel jPanelRondas1;
    // End of variables declaration//GEN-END:variables
}
